### ISSUE TITLE
logic problem with tag_gen.rb, patch to push related tags only once

### ISSUE THREAD

**Issue by mmehnert** [rfelix/my_jekyll_extensions#1]
```
diff --git a/tag_gen/tag_gen.rb b/tag_gen/tag_gen.rb
index 8bbc038..7facac6 100644
--- a/tag_gen/tag_gen.rb
+++ b/tag_gen/tag_gen.rb
@@ -22,7 +22,7 @@ module Jekyll
       related = []
       site.tags[tag].each do |post|
         post.tags.each do |rel| 
-          related.push(rel) unless rel == tag && related.include?(rel)
+          related.push(rel) unless rel == tag || related.include?(rel)
         end
       end      
       self.data['related'] = related unless related.empty?
```

**Comment by rfelix** [comment]
Ah damn, even though it's danc's stuff, he had it right in the beginning. I then suggested a few alterations and then proposed he compress the if statements with the unless and translated it badly! Thank's for that (/me embarrassed)! I'll be sure to let him know and fix it tomorrow ;)

**Comment by rfelix** [comment]
Just saw that danc also detected the problem and has resolved it. I only saw his pull request now. This issue has now been closed :)
